FROM nginx:latest
LABLE "Maintainer.name" = "varisha karim P Md"
LABLE "Date" = "06-07-2020"
RUN apt update -y && \
    apt install git -y && \
    apt install python -y && \
    apt install nano -y 
# VOLUME [ "volume1" ]
CMD [ "nginx" ]
EXPOSE 80/tcp
EXPOSE 443/tcp
